### ISSUE TITLE
the individual has no documentation

### ISSUE THREAD

**Issue by croussey** [Irstea/irrig#16]
FeatureOfInterest_Crop is not documented in the irrig ontology. Provide some explanation. For example.
This individual is an instance of the class sosa:FeatureOfInterest that represents a crop. The crop need to be irrigated. In our example the crop is a maize that growth in the arvalis plot in 2013.
add a rdfs:comment and a rdfs:label to clarify each individual that you have created.

**Comment by nqduy35** [comment]
Edit: 
- FeatureOfInterest_Crop and related individual of irrig ontology are documented.
