### ISSUE TITLE
defined classes problem

### ISSUE THREAD

**Issue by croussey** [Irstea/irrig#17]
there is a problem. I download the irrig version on the git. I have clowned the git. and the CropGrowthObservation is not a defined class. 
moreover the definition of crop growth observation does not inidcate that it is a defined class. I would expect that the rdfs:comments explained the axioms.

**Comment by croussey** [comment]
RainQuantityObservation - Act of carrying out an (Observation) Procedure to estimate or calculate a value of the Rain_Quantity Property of the Rain FeatureOfInterest. This act can be performed during the context acquisition or context processing phases of a context aware system. Links to a Sensor to describe what made the Observation and how; links to the Rain_Quantity ObservableProperty (Property) to describe what the result is an estimate of, and to the Rain FeatureOfInterest. When the act is made during the context processing phase the entry values of the procedure should be linked to the Observation by the wasDerivedFrom property.

this is a definition of Rain Quantity observation that is a defined class.
nothing mentioned that it is a defined class.
you should mention the axiom about the specific individual like FeatureOfInterest_Rain ... rethink about the definition is order to synthetise a good definition. Do not mebntion several time feature of interest and observable property...

**Comment by nqduy35** [comment]
Fix: 
- Add axioms to CropGrowthObservation
- Modify definitions of all Observation and Deduction according to the suggestions.
