### ISSUE TITLE
Precipitation property

### ISSUE THREAD

**Issue by croussey** [Irstea/irrig#18]
Precipitation is a feature of interest not a property... you should replace it by amount property or quantity property.

ObservableProperty_Rain_Intensity is not about quantity it is an Intensity property... you should not mixed...

TotalQuantityPerDay because it is perday amount is more about intensity than just quantity...

**Comment by nqduy35** [comment]
Edit: 
- irrig:PrecipitationProperty -> irrig:AmountProperty
- irrig:ObservableProperty_Rain_Intensity is individual of caso:Property and irrig;IntensityProperty
- irrig:ObservatbeProperty_Rain_TotalQuantityPerDay and irrig:ObservableProperty_Rain_Quantity are individuals of caso:Property and irrig:AmountProperty.
