### ISSUE TITLE
irrig:ObservationProperty_Crop_Growth definition

### ISSUE THREAD

**Issue by croussey** [Irstea/irrig#19]
You mention that the individual irrig:ObservationProperty_Crop_Growth should be an instance of the class caso:Property because it is associated to state value. In irrig this individual is not defined as a caso/property instance.

ObservableProperty_Crop_Stage is also associated to state so it should be a caso: Property instance... you could mentionned also that it is not used in our example and we use the other individual instead... You have to documente all the individual.

**Comment by nqduy35** [comment]
Edit:
- irrig:ObservableProperty_Crop_Growth and irrig:ObservableProperty_Crop_Stage are individuals of the classes: caso:Property and caso:GrowthProperty
- Defined all individuals in IRRIG.
